command_timeout=600

format = '''[$all](bg:black)[$fill $os $hostname [|](red bg:black) $shell [|](red bg:black) $time](bg:black)
$container$character'''


[line_break]
disabled = true

[fill]
style = "bg:black"
symbol = ' '

[nix_shell]
disabled = true
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'
format = 'via [☃️ $state( \($name\))](bold blue) '

[time]
disabled = false
use_12hr = true
style = "yellow dimmed bg:black"
format = '[$time]($style)'
time_format = '%I:%M:%S'

[hostname]
ssh_only = false
style = "cyan bg:black"
format = '[$ssh_symbol$hostname]($style)'
disabled = false

[shell]
format = '[$indicator]($style)'
fish_indicator = 'fish'
bash_indicator = 'bash'
style = "bold yellow bg:black"
disabled = false

[character]
success_symbol = '[>](bold green)'
error_symbol = '[✖](bold red)'

[os]
disabled = false
style = "bg:black"
format = "[$symbol]($style)"
symbols.Fedora = "󰣛"
symbols.Ubuntu = ""
symbols.Arch = "󰣇"
symbols.Debian = ""
symbols.Alpine = ""

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["*.compose.yaml", "compose.yaml", "docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
disabled = false

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "white bg:black"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

# Last param in the first line/row
# [cmd_duration]
# min_time = 1
# format = "took [$duration]($style)"
# disabled = false

[python]
symbol = ' '
pyenv_version_name = true
style = "blue bg:black"
# detect_extensions = []

[git_branch]
symbol = ' '
style = "red bg:black"

[directory]
style = "bg:black"
#[directory.substitutions]
#"~/Documents" = "󰈙 "
#"~/Downloads" = "󱑢 "
#"~/Music" = "󰎄 "
#"~/Pictures" = "󰄀 "
#"~/VM" = "  "
#"~/Pihole"= "󰷱 "
#"~/Playground" = " "

[container]
symbol = "󰮄 "
format = '[$symbol]($style)'

