command_timeout=600

format = '''$all$fill$shlvl$os $hostname [|](red) $shell [|](red) $time
$container$character'''

# [custom.foo]
# command = 'echo foo' # shows output of command
# detect_files = ['foo'] # can specify filters but wildcards are not supported
# when = ''' test "$SHLVL" = 5 '''
# format = ' transcending [$output]($style)'

[shlvl]
disabled = false
threshold = 2
format = '[󰄿 $shlvl](purple) [|](red) '

[line_break]
disabled = true

[fill]
symbol = ' '

[nix_shell]
disabled = false
format = 'via [ ](white) '

[time]
disabled = false
use_12hr = true
style = "yellow dimmed"
format = '[$time]($style)'
time_format = '%I:%M:%S'

[hostname]
ssh_only = false
style = "white"
format = '[$ssh_symbol$hostname]($style)'
disabled = false

[shell]
format = '[$indicator]($style)'
fish_indicator = 'fish'
bash_indicator = 'bash'
style = "yellow"
disabled = false

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'

[os]
disabled = false
format = "[$symbol]($style)"
symbols.Fedora = "󰣛"
symbols.Ubuntu = ""
symbols.Arch = "󰣇"
symbols.Debian = ""
symbols.Alpine = ""

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["*.compose.yaml", "compose.yaml", "docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
disabled = false

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "white"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

[status]
symbol = "✗"
not_found_symbol = "󰍉 Not Found"
not_executable_symbol = " Can't Execute E"
sigint_symbol = "󰂭 "
signal_symbol = "󱑽 "
success_symbol = ""
format = "[$symbol](fg:red)"
map_symbol = true
disabled = false

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "[󰔛 $duration]($style)"
disabled = false

[python]
symbol = ' '
pyenv_version_name = true
# detect_extensions = []

[git_branch]
symbol = ' '
style = "red"

#[directory.substitutions]
#"~/Documents" = "󰈙 "
#"~/Downloads" = "󱑢 "
#"~/Music" = "󰎄 "
#"~/Pictures" = "󰄀 "
#"~/VM" = "  "
#"~/Pihole"= "󰷱 "
#"~/Playground" = " "

[container]
symbol = "󰮄 "
format = '[$symbol]($style)'

