#!/bin/bash

alias cptheme='sudo cp ~/.themes/Marble-crispblue-dark/gnome-shell/gnome-shell.css /usr/share/themes/Marble-crispblue-dark/gnome-shell'
alias dci='distrobox create -i'
alias dcm='docker compose'
alias debi='distrobox enter debian-distrobox -nw -- fish -l'
alias ds=distrobox
alias dt='docker logs --tail 1000 -f'
alias edt='flatpak run org.gnome.TextEditor'
alias fedo='distrobox enter fedora-distrobox -nw -- fish -l'
alias flatdel='flatpak uninstall --delete-data'
alias pjp='protonvpn-cli c --cc JP'
alias pko='protonvpn-cli killswitch --off'
alias pus='protonvpn-cli c --cc US'
alias rm-pycache='find . -type d -name  "__pycache__" -exec rm -r {} +'
alias rmc='git rm --cached */__pycache__/*'
alias st='speedtest-cli --secure'

alias ls2='ls -TL=2'
alias ls3='ls -TL=3'
alias lsa='ls -T'
alias ll='ls -l'
alias lla='ls -lT'
alias ll2='ls -lTL=2'
alias ll3='ls -lTL=3'
alias la='ls -la'
alias la2='ls -laTL=2'
alias la3='ls -laTL=3'
alias lzd='lazydocker'
alias footconf='nano ~/.config/foot/foot.ini'
alias nano='micro'
alias ls='exa --icons -F -H --group-directories-first -1'
alias neofetch='fastfetch'
